name: CI

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    # GitHub Packagesへの公開のために.npmrcファイルをセットアップ
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://npm.pkg.github.com'

    # - name: Generate token
    #   id: generate_token
    #   uses: tibdex/github-app-token@v1
    #   with:
    #     app_id: ${{ secrets.APP_ID }}
    #     permissions: >-
    #       {"packages": "read"}
    #     repository: yosimurat/add_wasm
    #     private_key: ${{ secrets.PRIVATE_KEY }}

    - run: npm login --scope=@yosimurat --auth-type=legacy --registry=https://npm.pkg.github.com
    - run: echo yosimurat
    - run: echo ${{ secrets.GITHUB_TOKEN }}
    - name: Build npm package
      run: npm ci && npm run build
      # env:
      #   NPM_TOKEN: ${{ steps.generate_token.outputs.token }}
    - name: Publish npm package
      run: npm publish
      env:
        NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
